sudo: required
install:
  - pip install psycopg2
  - psql -c 'CREATE DATABASE json_test;' -U postgres
  - sudo make install
  - psql json_test -c 'CREATE EXTENSION "postgres-json-schema";' -U postgres
env:
  - DATABASE_URL=postgres:///json_test
services:
  - postgresql
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-server-dev-9.5
script: python test.py
language: python
